GET http://localhost:4000/user-api/getusers

###
GET http://localhost:4000/user-api/getuser/1

###
POST http://localhost:4000/user-api/create-user
Content-Type: application/json

{
    "id": 3,
    "name": "kiran",
    "age": 24
}

###
PUT http://localhost:4000/user-api/update-user
Content-Type: application/json

{
    "id": 1,
    "name": "ravi babu",
    "age": 21
}


###
DELETE http://localhost:4000/user-api/remove-user/3

###
GET http://localhost:4000/product-api/getproducts

###
GET http://localhost:4000/product-api/getproduct/100

###
POST http://localhost:4000/product-api/create-product